baseURL = "http://example.org/"
languageCode = "en-us"
title = "UK Digital Product Design Studio – Strike by Mindera"
theme= "agency-theme"

[markup.goldmark.renderer]
  unsafe= true

[menu]
  [[menu.main]]
    identifier = "how-we-help"
    name = "How we help"    
    url = "/how-we-help/"
    weight = 1